name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Generate Xcode project
      uses: xavierLowmiller/xcodegen-action@1.2.4
    - name: Run tests
      run: |
        xcodebuild test \
          -project Brankas.xcodeproj \
          -scheme Brankas \
          -destination "platform=macOS" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGN_IDENTITY=""
